## Dockerfile for product service
FROM java:8
FROM maven:alpine
#??
#COPY srv_build/usr/local/service/pom.xml srv_product/usr/local/service/pom.xml
#COPY srv_build/usr/local/service/src srv_product/usr/local/service/src
#CMD ["java","-cp", "target/my-app-1.0-SNAPSHOT.jar","com.mycompany.app.GalToLitTable"]